### ISSUE TITLE
/search has null in category everytime the page loads

### ISSUE THREAD

**Issue by spursycoder** [Atharva123987/Med-Pal#17]
Try searching by dragging the slider but not the category then u ll understand. The page must be refreshed for this.

**Comment by Atharva123987** [comment]
I asked you na what should be the category initially... You told empty

**Comment by spursycoder** [comment]
See whenever click on cardiologist and then go back to select category  at that time everything is loaded what when the page has loaded intially I think even if you search it's not loading anything so that means nothing is getting sent to the backend as speciality field

**Comment by Atharva123987** [comment]
What you want to send exactly to the back end tell me

**Comment by spursycoder** [comment]
The problem is when the page loads speciality is not initiated as a string

**Comment by Atharva123987** [comment]
It should be a string though......it cannot be null by any chance

**Comment by spursycoder** [comment]
Issue identified and fixed : Was declared incorrectly.
